# Recreate the requested tools and existing top-level packages.
brew "git"
brew "stow"
brew "uv"
brew "oh-my-posh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "fortune"
brew "cowsay"
brew "lolcat"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
brew "python@3.14"
brew "python-tk@3.14"
brew "vim"
cask "rectangle"
cask "karabiner-elements"
cask "squirrel"
